name: Build static site

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install pandas jinja2
      - name: Generate site
        run: python build.py
      - name: Commit built site
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add site
          git commit -m "Auto-generate site"
          git push
